app_auth/urls.py
from django_blog import views
from django.urls import path
from . import views

app_name = 'app_auth'

urlpatterns = [
    path('', views.user_login, name='index'),
    path('panel', views.dashboard, name='dashboard'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
]

django_blog/urls.py
from django_blog import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('auth/', include('app_auth.urls')),
    path('category/', include('app_category.urls')),
    path('post/', include('app_post.urls')),
    path('single_post/<str:slug>', views.single_post, name='single_post'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/frontend/layouts/app.html
<!DOCTYPE html>
{% load static %}
<html lang="en"> 
<head>
    <title>{% if post %}{{ post.title }}{%  else %}Django Blog - A Blog Made For Developers{% endif %}</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    <link rel="shortcut icon" href="favicon.ico"> 
    
    <!-- FontAwesome JS-->
    <script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js" integrity="sha384-eVEQC9zshBn0rFj4+TU78eNA19HMNigMviK/PU/FFjLXqa/GKPgX58rvt5Z8PLs7" crossorigin="anonymous"></script>
    
    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'css/theme-1.css' %}">

</head> 

<body>
    
    <header class="header text-center">	    
	    <h1 class="blog-name pt-lg-4 mb-0"><a href="{% url 'home' %}">{% if author_info.first_name %}{{ author_info.first_name }}{%  else %}{{ author_info.username }}{% endif %}'s Blog</a></h1>
        
	    <nav class="navbar navbar-expand-lg navbar-dark" >
           
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column" >
				<div class="profile-section pt-3 pt-lg-0">
				    <img class="profile-image mb-3 rounded-circle mx-auto" src="/media/{{ author_info.user_info.image }}" alt="{{ author_info.first_name }}" >			
					
					<div class="bio mb-3">{{ author_info.user_info.bio }}</div><!--//bio-->
					<ul class="social-list list-inline py-3 mx-auto">
			            <li class="list-inline-item"><a href="{{ author_info.user_info.twitter }}"><i class="fab fa-twitter fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="{{ author_info.user_info.facebook }}"><i class="fab fa-facebook fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="{{ author_info.user_info.instagram }}"><i class="fab fa-instagram fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="{{ author_info.user_info.linkedin }}"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="{{ author_info.user_info.github }}"><i class="fab fa-github-alt fa-fw"></i></a></li>
			        </ul><!--//social-list-->
			        <hr> 
				</div><!--//profile-section-->
				
				<ul class="navbar-nav flex-column text-left">
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'home' %}"><i class="fas fa-home fa-fw mr-2"></i> Homepage <span class="sr-only">(current)</span></a>
					</li>
					{% if user.is_authenticated %}
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'app_auth:dashboard' %}"><i class="fas fa-fw fa-tachometer-alt"></i> Dashboard <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'app_auth:logout' %}"><i class="fas fa-fw fa-cog"></i> Logout <span class="sr-only">(current)</span></a>
					</li>
					{% else %}
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'app_auth:login' %}"><i class="fas fa-fw fa-user"></i> Login <span class="sr-only">(current)</span></a>
					</li>
					{% endif %}
				</ul>
				
				<div class="my-2 my-md-3">
				    <a class="btn btn-primary" href="{{ author_info.user_info.facebook }}" target="_blank">Get in Touch</a>
				</div>
			</div>
		</nav>
    </header>
    
    <div class="main-wrapper">
	    
		{% block main_content %}
		{% endblock main_content %}
	    
	    <footer class="footer text-center py-2 theme-bg-dark">
		   
	        <!--/* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
                <small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
		   
	    </footer>
    
    </div><!--//main-wrapper-->


    
       
    <!-- Javascript -->          
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script> 
    <script src="{% static 'js/bootstrap.min.js' %}"></script>     
    

</body>
</html> 