app_auth/urls.py
from django_blog import views
from django.urls import path
from . import views

app_name = 'app_auth'

urlpatterns = [
    path('', views.user_login, name='index'),
    path('panel', views.dashboard, name='dashboard'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
]

app_post/urls.py
from django.urls import path
from app_post import views

app_name = 'app_post'

urlpatterns = [
    path('', views.show_post, name='show_post'),
    path('add/', views.add_post, name='add_post'),
    path('edit/<int:pk>', views.edit_post, name='edit_post'),
    path('delete/<int:pk>', views.delete_post, name='delete_post'),
]

django_blog/urls.py
from django_blog import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('auth/', include('app_auth.urls')),
    path('category/', include('app_category.urls')),
    path('post/', include('app_post.urls')),
    path('single_post/<str:slug>', views.single_post, name='single_post'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/backend/post/add_post.html
{% extends 'backend/layouts/app.html' %}

{% block main_content %}

<div class="col-xl-12 col-lg-12">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Add Category</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if messages %}
            {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %}" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            
            {% for field in form %}
            {% if field.errors %}
            <div class="alert alert-danger">{{ field.errors }}</div>
            {% endif %}
            {% endfor %}
            <form action="{% url 'app_post:add_post' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label>Title</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    <label>Content</label>
                    {{ form.content }}
                </div>
                <div class="form-group">
                    <label>Category</label>
                    {{ form.category }}
                </div>
                <div class="form-group">
                    <label>Featured Image</label>
                    {{ form.image }}
                </div>
                <input name="submit" type="submit" value="Add Post" class="btn btn-primary btn-block" />
            </form>
        </div>
    </div>
</div>

{% endblock main_content %}

templates/backend/post/edit_post.html
{% extends 'backend/layouts/app.html' %}

{% block main_content %}

<div class="col-xl-12 col-lg-12">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Edit Post</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if messages %}
            {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %}" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            
            {% for field in form %}
            {% if field.errors %}
            <div class="alert alert-danger">{{ field.errors }}</div>
            {% endif %}
            {% endfor %}
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label>Title</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    <label>Content</label>
                    {{ form.content }}
                </div>
                <div class="form-group">
                    <label>Category</label>
                    {{ form.category }}
                </div>
                <div class="form-group">
                    <label>Featured Image</label>
                    <img src="{{ form.image.value.url }}" width="100" height="100" alt=""><br>
                    <br>{{ form.image }}
                </div>
                <input name="submit" type="submit" value="Update Post" class="btn btn-primary btn-block" />
            </form>
        </div>
    </div>
</div>

{% endblock main_content %}

templates/backend/post/posts.html
{% extends 'backend/layouts/app.html' %}

{% block main_content %}

<div class="col-xl-12 col-lg-12">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">All Posts Created by You</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success" role="alert">
            {{ message }}
            </div>
            {% endfor %}
            {% endif %}

            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for post in data %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ post.title }}</td>
                            <td>{{ post.author.username }}</td>
                            <td>
                                <a class="btn btn-sm btn-success" href="{% url 'app_post:edit_post' pk=post.id %}"><i class="fas fa-edit"></i></a>
                                <a class="btn btn-sm btn-danger" href="{% url 'app_post:delete_post' pk=post.id %}"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock main_content %}